spring:
  datasource:
    url: jdbc:h2:~/test;MODE=MYSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
        use_sql_comments: true


logging.level.org.hibernate:
  SQL: debug
  type: trace
