logging:
  level:
    org:
      springframework:
        transaction.interceptor: TRACE
spring:
  datasource:
    url: jdbc:mysql://localhost:53306/playground
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  sql:
    init:
      platform: test
      mode: always
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
