logging:
  level:
    org:
      springframework:
        transaction.interceptor: TRACE
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:53306/playground
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: none
#    open-in-view: false
#  sql:
#    init:
#      platform: test
#      mode: always
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
