logging:
  level:
    org:
      springframework:
        transaction.interceptor: TRACE
      hibernate.type.descriptor.sql: trace

spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 8
  datasource:
#    url: jdbc:mysql://localhost:53306/playground
#    username: root
#    password: root
    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  sql:
    init:
      platform: test
      mode: always
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

